# Usar una imagen base de Go 1.22.5
FROM golang:1.23

# Configurar el entorno de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Compilar la aplicación
RUN go build -o main .

# Exponer el puerto
EXPOSE 8080

# Ejecutar la aplicación
CMD ["./main"]
